   "#!/usr/bin/env python3",
      "import argparse",
      "import json",
      "import math",
      "import sqlite3",
      "from datetime import datetime",
      "",
      "C = 299792458.0",
      "",
      "",
      "def clamp(x, lo, hi):",
      "    return max(lo, min(hi, x))",
      "",
      "",
      "def to_hz(value, unit):",
      "    unit = str(unit).lower()",
      "    scale = {'hz': 1.0, 'khz': 1e3, 'mhz': 1e6, 'ghz': 1e9}",
      "    if unit not in scale:",
      "        raise ValueError('Unsupported frequency unit: {}'.format(unit))",
      "    return float(value) * scale[unit]",
      "",
      "",
      "def to_m(value, unit):",
      "    unit = str(unit).lower()",
      "    scale = {'m': 1.0, 'cm': 0.01, 'mm': 0.001, 'ft': 0.3048, 'in': 0.0254}",
      "    if unit not in scale:",
      "        raise ValueError('Unsupported length unit: {}'.format(unit))",
      "    return float(value) * scale[unit]",
      "",
      "",
      "def rl_from_swr(swr):",
      "    swr = float(swr)",
      "    if swr <= 1.0:",
      "        return -99.0",
      "    rho = (swr - 1.0) / (swr + 1.0)",
      "    return round(-20.0 * math.log10(rho), 2)",
      "",
      "",
      "def swr_from_rl(rl_db):",
      "    rho = 10 ** (-abs(float(rl_db)) / 20.0)",
      "    if rho >= 1.0:",
      "        return 99.0",
      "    return round((1.0 + rho) / (1.0 - rho), 2)",
      "",
      "",
      "def plausible_gain_range(num_elements):",
      "    table = {",
      "        3: (6.0, 8.0),",
      "        4: (7.0, 9.0),",
      "        5: (8.0, 10.2),",
      "        6: (9.0, 11.2),",
      "        7: (10.0, 12.0),",
      "        8: (10.7, 12.6),",
      "        9: (11.2, 13.1),",
      "        10: (11.7, 13.6),",
      "        11: (12.1, 14.0),",
      "        12: (12.5, 14.4)",
      "    }",
      "    return table[num_elements]",
      "",
      "",
      "def default_roles(num_elements):",
      "    if num_elements == 3:",
      "        return ['reflector', 'driven', 'director_1']",
      "    if num_elements == 4:",
      "        return ['reflector', 'driven', 'director_1', 'director_2']",
      "    return ['reflector', 'xfrmr', 'driven', 'coupler'] + [f'director_{i}' for i in range(1, num_elements - 3)]",
      "",
      "",
      "def spacing_template_lambda(num_elements):",
      "    if num_elements == 3:",
      "        return [0.16, 0.12]",
      "    if num_elements == 4:",
      "        return [0.15, 0.10, 0.11]",
      "    values = [0.12, 0.08, 0.03, 0.10]",
      "    while len(values) < num_elements - 1:",
      "        values.append(max(0.08, values[-1] - 0.005))",
      "    return values[:num_elements - 1]",
      "",
      "",
      "class HybridOWADB:",
      "    def __init__(self, db_path='hybrid_owa.db'):",
      "        self.conn = sqlite3.connect(db_path)",
      "        self.conn.row_factory = sqlite3.Row",
      "",
      "    def init_db(self):",
      "        self.conn.executescript('''",
      "        CREATE TABLE IF NOT EXISTS designs (",
      "            id INTEGER PRIMARY KEY AUTOINCREMENT,",
      "            created_at TEXT NOT NULL,",
      "            request_json TEXT NOT NULL,",
      "            reasoning TEXT,",
      "            num_elements INTEGER NOT NULL,",
      "            center_frequency_hz REAL NOT NULL,",
      "            target_gain_dbi REAL,",
      "            predicted_gain_dbi REAL,",
      "            target_return_loss_db REAL,",
      "            predicted_return_loss_db REAL,",
      "            target_f_to_b_db REAL,",
      "            predicted_f_to_b_db REAL,",
      "            target_swr REAL,",
      "            predicted_swr REAL,",
      "            height_above_ground_m REAL,",
      "            boom_diameter_m REAL,",
      "            element_diameter_m REAL,",
      "            tapers_json TEXT,",
      "            geometry_json TEXT,",
      "            feed_impedance_ohm REAL,",
      "            polarization TEXT,",
      "            orientation TEXT,",
      "            notes TEXT",
      "        );",
      "        CREATE INDEX IF NOT EXISTS idx_designs_freq ON designs(center_frequency_hz);",
      "        CREATE INDEX IF NOT EXISTS idx_designs_elems ON designs(num_elements);",
      "        ''')",
      "        self.conn.commit()",
      "",
      "    def fetch_similar(self, req, limit=5):",
      "        rows = self.conn.execute(",
      "            'SELECT * FROM designs WHERE num_elements BETWEEN ? AND ? ORDER BY id DESC LIMIT 200',",
      "            (req['num_elements'] - 1, req['num_elements'] + 1)",
      "        ).fetchall()",
      "        scored = []",
      "        for row in rows:",
      "            row = dict(row)",
      "            freq_err = abs(row['center_frequency_hz'] - req['center_frequency_hz']) / req['center_frequency_hz']",
      "            gain_ref = row['predicted_gain_dbi'] if row['predicted_gain_dbi'] is not None else (row['target_gain_dbi'] or 0.0)",
      "            swr_ref = row['predicted_swr'] if row['predicted_swr'] is not None else (row['target_swr'] or 1.5)",
      "            fb_ref = row['predicted_f_to_b_db'] if row['predicted_f_to_b_db'] is not None else (row['target_f_to_b_db'] or 0.0)",
      "            gain_err = abs(gain_ref - req['gain']) / max(1.0, req['gain'])",
      "            swr_err = abs(swr_ref - req['swr']) / max(1.0, req['swr'])",
      "            fb_err = abs(fb_ref - req['front_to_back_ratio']) / max(1.0, req['front_to_back_ratio'])",
      "            elem_err = abs(row['num_elements'] - req['num_elements']) * 0.25",
      "            score = 0.40 * freq_err + 0.20 * gain_err + 0.15 * swr_err + 0.10 * fb_err + elem_err",
      "            scored.append((score, row))",
      "        scored.sort(key=lambda x: x[0])",
      "        return [item[1] for item in scored[:limit]]",
      "",
      "    def save_design(self, req, response):",
      "        cand = response['antenna_design']['candidate_design']",
      "        cur = self.conn.execute('''",
      "        INSERT INTO designs (",
      "            created_at, request_json, reasoning, num_elements, center_frequency_hz,",
      "            target_gain_dbi, predicted_gain_dbi,",
      "            target_return_loss_db, predicted_return_loss_db,",
      "            target_f_to_b_db, predicted_f_to_b_db,",
      "            target_swr, predicted_swr,",
      "            height_above_ground_m, boom_diameter_m, element_diameter_m,",
      "            tapers_json, geometry_json, feed_impedance_ohm, polarization, orientation, notes",
      "        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
      "        ''', (",
      "            datetime.utcnow().isoformat(timespec='seconds'),",
      "            json.dumps(req),",
      "            response['reasoning'],",
      "            req['num_elements'],",
      "            req['center_frequency_hz'],",
      "            req['gain'],",
      "            cand['predicted_gain_dbi'],",
      "            req['return_loss'],",
      "            cand['predicted_return_loss_db'],",
      "            req['front_to_back_ratio'],",
      "            cand['predicted_front_to_back_db'],",
      "            req['swr'],",
      "            cand['predicted_swr'],",
      "            req['height_above_ground_m'],",
      "            req['boom_diameter_m'],",
      "            req['element_diameter_m'],",
      "            json.dumps(req['tapers_m']),",
      "            json.dumps(cand['geometry']),",
      "            cand['feed_impedance_ohm'],",
      "            'horizontal',",
      "            'flat',",
      "            'saved by local CLI'",
      "        ))",
      "        self.conn.commit()",
      "        return cur.lastrowid",
      "",
      "    def list_designs(self, limit=20):",
      "        rows = self.conn.execute(",
      "            'SELECT id, created_at, num_elements, center_frequency_hz, predicted_gain_dbi, predicted_swr, predicted_f_to_b_db FROM designs ORDER BY id DESC LIMIT ?',",
      "            (limit,)",
      "        ).fetchall()",
      "        return [dict(r) for r in rows]",
      "",
      "",
      "def normalize_request(payload):",
      "    required = [",
      "        'num_elements',",
      "        'center_frequency',",
      "        'gain',",
      "        'front_to_back_ratio',",
      "        'swr',",
      "        'height_above_ground',",
      "        'boom_diameter',",
      "        'element_diameter',",
      "        'tapers'",
      "    ]",
      "    missing = [k for k in required if k not in payload or payload[k] in (None, '')]",
      "    if missing:",
      "        raise ValueError('Missing required fields: {}'.format(', '.join(missing)))",
      "",
      "    req = {}",
      "    req['num_elements'] = int(payload['num_elements'])",
      "    if req['num_elements'] < 3 or req['num_elements'] > 12:",
      "        raise ValueError('num_elements must be between 3 and 12')",
      "",
      "    req['center_frequency_hz'] = to_hz(payload['center_frequency'], payload.get('frequency_unit', 'MHz'))",
      "    req['gain'] = float(payload['gain'])",
      "    req['front_to_back_ratio'] = float(payload['front_to_back_ratio'])",
      "    req['swr'] = float(payload['swr'])",
      "    if req['swr'] <= 1.0:",
      "        raise ValueError('swr must be greater than 1.0')",
      "",
      "    if payload.get('return_loss') in (None, ''):",
      "        req['return_loss'] = None",
      "    else:",
      "        req['return_loss'] = -abs(float(payload['return_loss']))",
      "",
      "    req['height_above_ground_m'] = to_m(payload['height_above_ground'], payload.get('height_unit', 'ft'))",
      "    req['boom_diameter_m'] = to_m(payload['boom_diameter'], payload.get('boom_diameter_unit', 'in'))",
      "    req['element_diameter_m'] = to_m(payload['element_diameter'], payload.get('element_diameter_unit', 'in'))",
      "",
      "    tapers = payload['tapers']",
      "    if isinstance(tapers, str):",
      "        tapers = [float(x.strip()) for x in tapers.split(',') if x.strip()]",
      "    taper_unit = payload.get('taper_unit', payload.get('element_diameter_unit', 'in'))",
      "    req['tapers_m'] = [round(to_m(x, taper_unit), 6) for x in tapers]",
      "    if req['tapers_m'] != sorted(req['tapers_m'], reverse=True):",
      "        raise ValueError('tapers must be ordered largest to smallest')",
      "",
      "    req['polarization'] = 'horizontal'",
      "    req['orientation'] = 'flat'",
      "    return req",
      "",
      "",
      "def generate_geometry(req):",
      "    wavelength = C / req['center_frequency_hz']",
      "    roles = default_roles(req['num_elements'])",
      "    spacing_l = spacing_template_lambda(req['num_elements'])",
      "    spacing_m = [round(x * wavelength, 4) for x in spacing_l]",
      "",
      "    positions = [0.0]",
      "    for s in spacing_m:",
      "        positions.append(round(positions[-1] + s, 4))",
      "",
      "    lengths = []",
      "    for role in roles:",
      "        if role == 'reflector':",
      "            base = 0.500",
      "        elif role == 'xfrmr':",
      "            base = 0.486",
      "        elif role == 'driven':",
      "            base = 0.475",
      "        elif role == 'coupler':",
      "            base = 0.466",
      "        else:",
      "            idx = int(role.split('_')[1])",
      "            base = max(0.418, 0.455 - 0.006 * (idx - 1))",
      "",
      "        boom_factor = min(0.010, req['boom_diameter_m'] / wavelength)",
      "        elem_factor = min(0.012, req['element_diameter_m'] / wavelength)",
      "        corrected = base * wavelength * (1.0 - 0.35 * boom_factor - 0.55 * elem_factor)",
      "        lengths.append(round(corrected, 4))",
      "",
      "    return {",
      "        'wavelength_m': round(wavelength, 4),",
      "        'roles': roles,",
      "        'element_lengths_m': lengths,",
      "        'element_spacings_m': spacing_m,",
      "        'positions_m': positions,",
      "        'boom_length_m': round(sum(spacing_m), 4)",
      "    }",
      "",
      "",
      "def evaluate_request(req, similar_rows):",
      "    warnings = []",
      "    low_gain, high_gain = plausible_gain_range(req['num_elements'])",
      "    target_rl = req['return_loss'] if req['return_loss'] is not None else rl_from_swr(req['swr'])",
      "",
      "    if req['return_loss'] is not None:",
      "        eq_swr = swr_from_rl(req['return_loss'])",
      "        if abs(eq_swr - req['swr']) > 0.25:",
      "            warnings.append('Return loss {} dB and SWR {} are not tightly consistent. RL implies SWR about {}.'.format(req['return_loss'], req['swr'], eq_swr))",
      "",
      "    wavelength = C / req['center_frequency_hz']",
      "    height_lambda = req['height_above_ground_m'] / wavelength",
      "    if height_lambda < 0.5:",
      "        warnings.append('Height is only {} lambda. Horizontal pattern and F/B may shift significantly.'.format(round(height_lambda, 2)))",
      "",
      "    predicted_gain = clamp(req['gain'], low_gain, high_gain)",
      "    if req['gain'] > high_gain:",
      "        warnings.append('Target gain {} dBi is above this first-pass range for {} elements. Estimated upper region is about {} dBi.'.format(req['gain'], req['num_elements'], high_gain))",
      "    predicted_gain = round(predicted_gain, 2)",
      "",
      "    fb_limit = min(40.0, 11.0 + 2.3 * req['num_elements'])",
      "    predicted_fb = round(clamp(req['front_to_back_ratio'], 8.0, fb_limit), 2)",
      "    if req['front_to_back_ratio'] > fb_limit:",
      "        warnings.append('Target F/B exceeds simple model limit. Clamped estimate to {} dB.'.format(predicted_fb))",
      "",
      "    predicted_swr = round(clamp(req['swr'], 1.05, 2.0), 2)",
      "    predicted_rl = rl_from_swr(predicted_swr)",
      "",
      "    similar_summary = []",
      "    if similar_rows:",
      "        nearest = similar_rows[0]",
      "        if nearest.get('predicted_gain_dbi') is not None:",
      "            predicted_gain = round(0.75 * predicted_gain + 0.25 * nearest['predicted_gain_dbi'], 2)",
      "        for row in similar_rows:",
      "            similar_summary.append({",
      "                'id': row['id'],",
      "                'num_elements': row['num_elements'],",
      "                'center_frequency_mhz': round(row['center_frequency_hz'] / 1e6, 4),",
      "                'predicted_gain_dbi': row['predicted_gain_dbi'],",
      "                'predicted_swr': row['predicted_swr'],",
      "                'predicted_f_to_b_db': row['predicted_f_to_b_db']",
      "            })",
      "",
      "    geometry = generate_geometry(req)",
      "    return {",
      "        'predicted_gain_dbi': predicted_gain,",
      "        'predicted_return_loss_db': predicted_rl,",
      "        'predicted_front_to_back_db': predicted_fb,",
      "        'predicted_swr': predicted_swr,",
      "        'feed_impedance_ohm': 50.0,",
      "        'geometry': geometry,",
      "        'warnings': warnings,",
      "        'similar_designs_used': similar_summary,",
      "        'target_return_loss_db_used': target_rl",
      "    }",
      "",
      "",
      "def build_response(req, db, save=False):",
      "    similar = db.fetch_similar(req, limit=5)",
      "    result = evaluate_request(req, similar)",
      "",
      "    reasoning_parts = []",
      "    reasoning_parts.append('Validated a horizontal hybrid OWA request for {} elements at {} MHz.'.format(req['num_elements'], round(req['center_frequency_hz'] / 1e6, 4)))",
      "    reasoning_parts.append('Included installation height, boom diameter, element diameter, and {} taper entries.'.format(len(req['tapers_m'])))",
      "    if similar:",
      "        ids = ', '.join(str(x['id']) for x in similar)",
      "        reasoning_parts.append('Compared against similar SQLite records: {}.'.format(ids))",
      "    else:",
      "        reasoning_parts.append('No close prior records were found, so the result is based on first-pass rule-based estimation.')",
      "    if result['warnings']:",
      "        reasoning_parts.append('Warnings: ' + ' '.join(result['warnings']))",
      "",
      "    response = {",
      "        'reasoning': ' '.join(reasoning_parts),",
      "        'antenna_design': {",
      "            'request_normalized': {",
      "                'num_elements': req['num_elements'],",
      "                'center_frequency_mhz': round(req['center_frequency_hz'] / 1e6, 6),",
      "                'gain_dbi': req['gain'],",
      "                'return_loss_db': req['return_loss'],",
      "                'front_to_back_db': req['front_to_back_ratio'],",
      "                'swr': req['swr'],",
      "                'height_above_ground_m': round(req['height_above_ground_m'], 4),",
      "                'boom_diameter_m': round(req['boom_diameter_m'], 6),",
      "                'element_diameter_m': round(req['element_diameter_m'], 6),",
      "                'tapers_m': req['tapers_m'],",
      "                'polarization': 'horizontal',",
      "                'orientation': 'flat'",
      "            },",
      "            'candidate_design': {",
      "                'num_elements': req['num_elements'],",
      "                'frequency_mhz': round(req['center_frequency_hz'] / 1e6, 6),",
      "                'predicted_gain_dbi': result['predicted_gain_dbi'],",
      "                'predicted_return_loss_db': result['predicted_return_loss_db'],",
      "                'predicted_front_to_back_db': result['predicted_front_to_back_db'],",
      "                'predicted_swr': result['predicted_swr'],",
      "                'feed_impedance_ohm': result['feed_impedance_ohm'],",
      "                'geometry': result['geometry'],",
      "                'similar_designs_used': result['similar_designs_used']",
      "            }",
      "        },",
      "        'suggestions': result['warnings'] if result['warnings'] else [",
      "            'Use this as a first-pass build or simulation baseline.',",
      "            'Tune parasitics first, then coupling, then driven element resonance.',",
      "            'Save measured results back into the database to improve future comparisons.'",
      "        ],",
      "        'database_action': 'retrieved similar designs from local SQLite database; design not saved',",
      "        'save_confirm': False",
      "    }",
      "",
      "    if save:",
      "        record_id = db.save_design(req, response)",
      "        response['database_action'] = 'retrieved similar designs and saved new design as record #{}'.format(record_id)",
      "        response['save_confirm'] = True",
      "",
      "    return response",
      "",
      "",
      "def prompt_user():",
      "    payload = {}",
      "    payload['num_elements'] = int(input('Number of elements (3-12): ').strip())",
      "    payload['center_frequency'] = float(input('Center frequency: ').strip())",
      "    payload['frequency_unit'] = input('Frequency unit [MHz]: ').strip() or 'MHz'",
      "    payload['gain'] = float(input('Target gain dBi: ').strip())",
      "    rl = input('Target return loss dB, optional: ').strip()",
      "    payload['return_loss'] = float(rl) if rl else None",
      "    payload['front_to_back_ratio'] = float(input('Target F/B dB: ').strip())",
      "    payload['swr'] = float(input('Target SWR: ').strip())",
      "    payload['height_above_ground'] = float(input('Height above ground: ').strip())",
      "    payload['height_unit'] = input('Height unit [ft]: ').strip() or 'ft'",
      "    payload['boom_diameter'] = float(input('Boom diameter: ').strip())",
      "    payload['boom_diameter_unit'] = input('Boom diameter unit [in]: ').strip() or 'in'",
      "    payload['element_diameter'] = float(input('Element root/reference diameter: ').strip())",
      "    payload['element_diameter_unit'] = input('Element diameter unit [in]: ').strip() or 'in'",
      "    tapers = input('Tapers list largest-to-smallest, comma separated: ').strip()",
      "    payload['tapers'] = [float(x.strip()) for x in tapers.split(',') if x.strip()]",
      "    payload['taper_unit'] = input('Taper unit [in]: ').strip() or 'in'",
      "    return payload",
      "",
      "",
      "def main():",
      "    parser = argparse.ArgumentParser(description='Hybrid OWA local design system')",
      "    parser.add_argument('--db', default='hybrid_owa.db', help='SQLite database path')",
      "    sub = parser.add_subparsers(dest='cmd', required=True)",
      "",
      "    sub.add_parser('init-db', help='Initialize SQLite database')",
      "",
      "    p_design = sub.add_parser('design', help='Run a design request')",
      "    p_design.add_argument('--input', help='Path to JSON request file')",
      "    p_design.add_argument('--interactive', action='store_true', help='Prompt for values interactively')",
      "    p_design.add_argument('--save', action='store_true', help='Save design result')",
      "",
      "    p_list = sub.add_parser('list', help='List saved designs')",
      "    p_list.add_argument('--limit', type=int, default=20)",
      "",
      "    args = parser.parse_args()",
      "    db = HybridOWADB(args.db)",
      "    db.init_db()",
      "",
      "    if args.cmd == 'init-db':",
      "        print(json.dumps({",
      "            'reasoning': 'Initialized the local SQLite database for hybrid OWA designs.',",
      "            'antenna_design': {'database': args.db},",
      "            'suggestions': ['Next run the design command with --interactive or --input request.json'],",
      "            'database_action': 'created or verified SQLite tables',",
      "            'save_confirm': False",
      "        }, indent=2))",
      "        return",
      "",
      "    if args.cmd == 'list':",
      "        rows = db.list_designs(limit=args.limit)",
      "        print(json.dumps({",
      "            'reasoning': 'Retrieved {} saved records from the local SQLite database.'.format(len(rows)),",
      "            'antenna_design': {'saved_designs': rows},",
      "            'suggestions': ['Use these records as references for future designs.'],",
      "            'database_action': 'retrieved recent saved designs',",
      "            'save_confirm': False",
      "        }, indent=2))",
      "        return",
      "",
      "    if args.cmd == 'design':",
      "        if args.interactive:",
      "            payload = prompt_user()",
      "        elif args.input:",
      "            with open(args.input, 'r', encoding='utf-8') as f:",
      "                payload = json.load(f)",
      "        else:",
      "            raise SystemExit('Use --interactive or --input <file.json>')",
      "",
      "        req = normalize_request(payload)",
      "        response = build_response(req, db, save=args.save)",
      "        print(json.dumps(response, indent=2))",
      "        return",
      "",
      "",
      "if __name__ == '__main__':",
      "    main()"
