import os
import re
from pathlib import Path
from typing import Dict, List, Tuple

from models import Antenna, Environment, Scenario, FrequencyResult, SimulationResult


def _fmt(value: float) -> str:
    return f"{value:.6f}"


def _float_tokens(line: str):
    vals = re.findall(r'[-+]?\d*\.?\d+(?:[Ee][-+]?\d+)?', line)
    out = []
    for v in vals:
        try:
            out.append(float(v))
        except:
            pass
    return out


def cumulative_x_positions(antenna: Antenna) -> Dict[str, float]:
    positions = {}
    x = 0.0
    for i, el in enumerate(sorted(antenna.elements, key=lambda e: e.sort_order)):
        if i == 0:
            x = 0.0
        else:
            x += el.spacing_from_prev_ft
        positions[el.name] = x
    return positions


def _gw(tag: int, segs: int, x1: float, y1: float, z1: float, x2: float, y2: float, z2: float, radius_ft: float) -> str:
    return f"GW {tag} {segs} {_fmt(x1)} {_fmt(y1)} {_fmt(z1)} {_fmt(x2)} {_fmt(y2)} {_fmt(z2)} {_fmt(radius_ft)}"


def build_nec_text(antenna: Antenna, environment: Environment, scenario: Scenario):
    lines = []
    lines.append(f"CM Generated by antenna designer")
    lines.append(f"CM Antenna: {antenna.name}")
    lines.append(f"CM Scenario: {scenario.name}")
    lines.append(f"CM Height: {scenario.height_ft} ft")
    lines.append("CE")

    tag = 1
    tag_map = {}
    xmap = cumulative_x_positions(antenna)

    # antenna wires
    for el in sorted(antenna.elements, key=lambda e: e.sort_order):
        if not el.enabled:
            continue
        x = xmap[el.name]
        y1 = -el.length_ft / 2.0
        y2 = el.length_ft / 2.0
        z = scenario.height_ft
        segs = 21
        radius_ft = (el.diameter_in / 12.0) / 2.0
        lines.append(_gw(tag, segs, x, y1, z, x, y2, z, radius_ft))
        tag_map[el.name] = {"tag": tag, "segments": segs, "x": x}
        tag += 1

    # simple nearby objects
    for obj in environment.objects:
        if not obj.enabled or not obj.conductive:
            continue

        if obj.kind == "tower":
            # simple vertical wire
            lines.append(_gw(tag, 31, obj.x_ft, obj.y_ft, obj.z_ft, obj.x_ft, obj.y_ft, obj.z_ft + obj.height_ft, 0.05))
            tag += 1

        elif obj.kind in ("garage", "garage_door"):
            # simple rectangular frame in Y/Z plane
            x = obj.x_ft
            y = obj.y_ft
            z = obj.z_ft
            w = obj.length_ft
            h = obj.height_ft
            y1 = y - w / 2.0
            y2 = y + w / 2.0
            z1 = z
            z2 = z + h
            lines.append(_gw(tag, 11, x, y1, z1, x, y2, z1, 0.02)); tag += 1
            lines.append(_gw(tag, 11, x, y2, z1, x, y2, z2, 0.02)); tag += 1
            lines.append(_gw(tag, 11, x, y2, z2, x, y1, z2, 0.02)); tag += 1
            lines.append(_gw(tag, 11, x, y1, z2, x, y1, z1, 0.02)); tag += 1

        elif obj.kind in ("car", "vehicle"):
            # simple box frame
            x1 = obj.x_ft - obj.length_ft / 2.0
            x2 = obj.x_ft + obj.length_ft / 2.0
            y1 = obj.y_ft - obj.width_ft / 2.0
            y2 = obj.y_ft + obj.width_ft / 2.0
            z1 = obj.z_ft
            z2 = obj.z_ft + obj.height_ft

            # bottom rectangle
            lines.append(_gw(tag, 9, x1, y1, z1, x2, y1, z1, 0.02)); tag += 1
            lines.append(_gw(tag, 9, x2, y1, z1, x2, y2, z1, 0.02)); tag += 1
            lines.append(_gw(tag, 9, x2, y2, z1, x1, y2, z1, 0.02)); tag += 1
            lines.append(_gw(tag, 9, x1, y2, z1, x1, y1, z1, 0.02)); tag += 1

            # top rectangle
            lines.append(_gw(tag, 9, x1, y1, z2, x2, y1, z2, 0.02)); tag += 1
            lines.append(_gw(tag, 9, x2, y1, z2, x2, y2, z2, 0.02)); tag += 1
            lines.append(_gw(tag, 9, x2, y2, z2, x1, y2, z2, 0.02)); tag += 1
            lines.append(_gw(tag, 9, x1, y2, z2, x1, y1, z2, 0.02)); tag += 1

            # verticals
            lines.append(_gw(tag, 5, x1, y1, z1, x1, y1, z2, 0.02)); tag += 1
            lines.append(_gw(tag, 5, x2, y1, z1, x2, y1, z2, 0.02)); tag += 1
            lines.append(_gw(tag, 5, x2, y2, z1, x2, y2, z2, 0.02)); tag += 1
            lines.append(_gw(tag, 5, x1, y2, z1, x1, y2, z2, 0.02)); tag += 1

        elif obj.kind in ("shed", "house", "building"):
            # simple nearest wall frame
            x = obj.x_ft
            y = obj.y_ft
            z = obj.z_ft
            w = obj.length_ft
            h = obj.height_ft
            y1 = y - w / 2.0
            y2 = y + w / 2.0
            z1 = z
            z2 = z + h
            lines.append(_gw(tag, 11, x, y1, z1, x, y2, z1, 0.03)); tag += 1
            lines.append(_gw(tag, 11, x, y2, z1, x, y2, z2, 0.03)); tag += 1
            lines.append(_gw(tag, 11, x, y2, z2, x, y1, z2, 0.03)); tag += 1
            lines.append(_gw(tag, 11, x, y1, z2, x, y1, z1, 0.03)); tag += 1

    lines.append("GE 0")

    if environment.ground_kind == "perfect":
        lines.append("GN 1")
    else:
        # real ground
        lines.append(f"GN 2 0 0 0 {_fmt(environment.dielectric_constant)} {_fmt(environment.conductivity)}")

    # source on driven element center segment
    de_info = tag_map["DE"]
    source_tag = de_info["tag"]
    source_seg = (de_info["segments"] // 2) + 1
    lines.append(f"EX 0 {source_tag} {source_seg} 0 1.0 0.0")

    # frequency sweep
    freqs = scenario.frequencies_mhz
    if len(freqs) == 1:
        lines.append(f"FR 0 1 0 0 {_fmt(freqs[0])} 0.0")
    else:
        start = min(freqs)
        step = freqs[1] - freqs[0]
        lines.append(f"FR 0 {len(freqs)} 0 0 {_fmt(start)} {_fmt(step)}")

    # one forward RP and one rear RP
    # theta=90, phi=0
    lines.append("RP 0 1 1 1000 90.0 0.0 0.0 0.0 1000.0")
    # theta=90, phi=180
    lines.append("RP 0 1 1 1000 90.0 180.0 0.0 0.0 1000.0")

    lines.append("EN")

    return "\n".join(lines) + "\n", source_tag, source_seg


def write_nec_file(antenna: Antenna, environment: Environment, scenario: Scenario, out_dir: str = "nec_files"):
    Path(out_dir).mkdir(parents=True, exist_ok=True)
    base = f"{antenna.name}_{scenario.name}".replace(" ", "_")
    nec_path = Path(out_dir) / f"{base}.nec"
    out_path = Path(out_dir) / f"{base}.out"

    text, source_tag, source_seg = build_nec_text(antenna, environment, scenario)

    with open(nec_path, "w") as f:
        f.write(text)

    return {
        "nec_path": str(nec_path),
        "out_path": str(out_path),
        "source_tag": source_tag,
        "source_seg": source_seg,
    }


def parse_nec_output(output_path: str, expected_freqs: List[float], source_tag: int, source_seg: int):
    if not os.path.exists(output_path):
        return []

    with open(output_path, "r", errors="ignore") as f:
        text = f.read()

    freq_blocks = re.split(r'(?=FREQUENCY\s*=\s*[-+]?\d)', text, flags=re.IGNORECASE)
    results = []

    for block in freq_blocks:
        m = re.search(r'FREQUENCY\s*=\s*([-+]?\d*\.?\d+(?:[Ee][-+]?\d+)?)\s*MHZ', block, flags=re.IGNORECASE)
        if not m:
            continue
        freq = float(m.group(1))

        r_ohms = None
        x_ohms = None
        gain_fwd = None
        gain_rear = None

        lines = block.splitlines()

        # parse impedance from antenna input parameters table
        for line in lines:
            nums = _float_tokens(line)
            if len(nums) >= 8:
                try:
                    tag_val = int(nums[0])
                    seg_val = int(nums[1])
                except:
                    continue
                if tag_val == source_tag and seg_val == source_seg:
                    # expected row:
                    # tag seg Vreal Vimag Ireal Iimag Zreal Zimag ...
                    r_ohms = float(nums[6])
                    x_ohms = float(nums[7])
                    break

        # parse forward/rear gains from the two RP tables
        rp_rows = []
        in_rp = False
        for line in lines:
            if "RADIATION PATTERNS" in line.upper():
                in_rp = True
                continue
            if in_rp:
                nums = _float_tokens(line)
                if len(nums) >= 5:
                    rp_rows.append(nums)
                    in_rp = False

        if len(rp_rows) >= 1:
            # theta phi ... total_gain...
            gain_fwd = float(rp_rows[0][4])
        if len(rp_rows) >= 2:
            gain_rear = float(rp_rows[1][4])

        if r_ohms is not None and x_ohms is not None:
            if gain_fwd is None:
                gain_fwd = 0.0
            if gain_rear is None:
                gain_rear = -10.0
            fb = gain_fwd - gain_rear

            # simple SWR calc
            z0 = 50.0
            num = ((r_ohms - z0) ** 2 + x_ohms ** 2) ** 0.5
            den = ((r_ohms + z0) ** 2 + x_ohms ** 2) ** 0.5
            gamma = num / den if den else 0.999
            gamma = min(gamma, 0.9999)
            swr = (1 + gamma) / (1 - gamma)

            results.append(FrequencyResult(
                freq_mhz=round(freq, 3),
                r_ohms=round(r_ohms, 3),
                x_ohms=round(x_ohms, 3),
                swr_50=round(swr, 3),
                gain_dbi=round(gain_fwd, 3),
                rear_gain_dbi=round(gain_rear, 3),
                fb_db=round(fb, 3),
                notes="parsed NEC output"
            ))

    # sort to frequency order
    results.sort(key=lambda x: x.freq_mhz)

    # only accept if we got something useful
    if not results:
        return []

    return results
